### ISSUE TITLE
Couldn't connect to host 

### ISSUE THREAD

**Issue by timreichen** [niutech/node.php#19]
The demo link in the [readme](https://github.com/niutech/node.php) has the same problem as I have on my server. I can install and start the server but when I set the node.php?path=xxx it tells me the following error:

`Error requesting xxx: couldn't connect to host.`

How to solve this error?

**Comment by w3adventures** [comment]
I belive this issue is connected to hosting service.
Sometimes when I visit [http://juvenia.info/node_modules/jt-js-sample/](http://juvenia.info/node_modules/jt-js-sample/) it shows
`Error: couldn't connect to host`
But after refreshing few times it shows basic Node.php info:
_Hello from node.js on PHP shared hosting!_

On my test Node.php here [http://nodejs.w3adventures.com/](http://nodejs.w3adventures.com/) it works fine.
In past 20 days I just had to restart node server one time.
Routing works fine like this [http://nodejs.w3adventures.com/?path=xxx](http://nodejs.w3adventures.com/?path=xxx) and also [http://nodejs.w3adventures.com/xxx](http://nodejs.w3adventures.com/xxx) because of htaccess usage.

**Comment by timreichen** [comment]
Thanks for your answer. I could not make it work for now. Could you post the example project source somewhere?

**Comment by w3adventures** [comment]
All files can be downloaded [here](http://nodejs.w3adventures.com/files/nodephp.zip).
CSS and frontend JavaScript are in root _css_ and _js_ folder while backend files are in _node_modules/nodejs/_ containing main index.js and EJS templates in _views_ folder.

**Comment by niutech** [comment]
Please check the new [Troubleshooting section of README](https://github.com/niutech/node.php#troubleshooting)
